name: Show information about context Github
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs: 
	display:
		runs-on: ubuntu-latest
		steps:
			- name: Show Github context
			  run: |
					echo "${{ toJson(github) }} "
					echo "-------------------------------------""
					echo $GITHUB_WORKSPACE