name: Listar Ambientes

on:
  workflow_dispatch: # Isso permite acionar manualmente o fluxo

jobs:
  listar_ambientes:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar c贸digo
      uses: actions/checkout@v3 # Isso verifica o c贸digo do reposit贸rio

    - name: Listar Ambientes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Isso permite acessar a API do GitHub
      run: |
        repo_slug="${{ github.repository }}"
        echo "Listando ambientes do reposit贸rio: $repo_slug"
        
        # Fazer uma chamada para a API do GitHub para listar ambientes
        get_environments=$(curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$repo_slug/environments")
        
        # Exibir os resultados
        echo $get_environments | jq -c '.environments.[]'
        #_environments | jq -c '.environments.[]'); do
        #    echo $env | jq -r '.name'
        #done