name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - run: echo "${{ github.workspace }} or ${{ github.path }}""
      - run: 