name: call a script
on: workflow_dispatch
jobs:
  call-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
          chmod +x scripts/teste.sh
          bash -e scripts/teste.sh      